[project]
name = "cojt_pattern"
version = "0.1.0"
repository = "https://github.com/Ryoga-exe/cojt-pattern"

[build]
source = "src"
target = { type = "directory", path = "target" }
clock_type = "posedge"
reset_type = "sync_high"
omit_project_prefix = true
implicit_parameter_types = ["string"]
expand_inside_operation = true

[test]
waveform_target = { type = "directory", path = "wave" }
waveform_format = "fst"

